//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  timeline: Timeline;
  timelineConnection: TimelineConnection;
  projetos: Projetos;
  projetosConnection: ProjetosConnection;
  skills: Skills;
  skillsConnection: SkillsConnection;
  posts: Posts;
  postsConnection: PostsConnection;
  atualizacoes: Atualizacoes;
  atualizacoesConnection: AtualizacoesConnection;
  agora: Agora;
  agoraConnection: AgoraConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTimelineArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTimelineConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TimelineFilter>;
};


export type QueryProjetosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjetosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjetosFilter>;
};


export type QuerySkillsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySkillsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillsFilter>;
};


export type QueryPostsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
};


export type QueryAtualizacoesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAtualizacoesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AtualizacoesFilter>;
};


export type QueryAgoraArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAgoraConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AgoraFilter>;
};

export type DocumentFilter = {
  timeline?: InputMaybe<TimelineFilter>;
  projetos?: InputMaybe<ProjetosFilter>;
  skills?: InputMaybe<SkillsFilter>;
  posts?: InputMaybe<PostsFilter>;
  atualizacoes?: InputMaybe<AtualizacoesFilter>;
  agora?: InputMaybe<AgoraFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Timeline | Projetos | Skills | Posts | Atualizacoes | Agora | Folder;

export type Timeline = Node & Document & {
  __typename?: 'Timeline';
  cargo: Scalars['String']['output'];
  empresa: Scalars['String']['output'];
  empresa_url?: Maybe<Scalars['String']['output']>;
  inicio: Scalars['String']['output'];
  fim?: Maybe<Scalars['String']['output']>;
  local?: Maybe<Scalars['String']['output']>;
  tipo?: Maybe<Scalars['String']['output']>;
  resumo?: Maybe<Scalars['String']['output']>;
  destaques?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  destaque?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TimelineFilter = {
  cargo?: InputMaybe<StringFilter>;
  empresa?: InputMaybe<StringFilter>;
  empresa_url?: InputMaybe<StringFilter>;
  inicio?: InputMaybe<DatetimeFilter>;
  fim?: InputMaybe<DatetimeFilter>;
  local?: InputMaybe<StringFilter>;
  tipo?: InputMaybe<StringFilter>;
  resumo?: InputMaybe<StringFilter>;
  destaques?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  destaque?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TimelineConnectionEdges = {
  __typename?: 'TimelineConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Timeline>;
};

export type TimelineConnection = Connection & {
  __typename?: 'TimelineConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TimelineConnectionEdges>>>;
};

export type Projetos = Node & Document & {
  __typename?: 'Projetos';
  titulo: Scalars['String']['output'];
  subtitulo?: Maybe<Scalars['String']['output']>;
  status: Scalars['String']['output'];
  inicio: Scalars['String']['output'];
  fim?: Maybe<Scalars['String']['output']>;
  cliente?: Maybe<Scalars['String']['output']>;
  papel: Scalars['String']['output'];
  resumo: Scalars['String']['output'];
  problema?: Maybe<Scalars['String']['output']>;
  abordagem?: Maybe<Scalars['String']['output']>;
  resultado?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  destaque?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjetosBodyVideoEmbedFilter = {
  src?: InputMaybe<StringFilter>;
  legenda?: InputMaybe<StringFilter>;
};

export type ProjetosBodyFilter = {
  VideoEmbed?: InputMaybe<ProjetosBodyVideoEmbedFilter>;
};

export type ProjetosFilter = {
  titulo?: InputMaybe<StringFilter>;
  subtitulo?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  inicio?: InputMaybe<DatetimeFilter>;
  fim?: InputMaybe<DatetimeFilter>;
  cliente?: InputMaybe<StringFilter>;
  papel?: InputMaybe<StringFilter>;
  resumo?: InputMaybe<StringFilter>;
  problema?: InputMaybe<StringFilter>;
  abordagem?: InputMaybe<StringFilter>;
  resultado?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  destaque?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<ProjetosBodyFilter>;
};

export type ProjetosConnectionEdges = {
  __typename?: 'ProjetosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projetos>;
};

export type ProjetosConnection = Connection & {
  __typename?: 'ProjetosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjetosConnectionEdges>>>;
};

export type Skills = Node & Document & {
  __typename?: 'Skills';
  nome: Scalars['String']['output'];
  categoria: Scalars['String']['output'];
  area: Scalars['String']['output'];
  nivel?: Maybe<Scalars['String']['output']>;
  instituicao?: Maybe<Scalars['String']['output']>;
  instituicao_url?: Maybe<Scalars['String']['output']>;
  ano?: Maybe<Scalars['Float']['output']>;
  credencial_url?: Maybe<Scalars['String']['output']>;
  descricao?: Maybe<Scalars['String']['output']>;
  destaque?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type SkillsFilter = {
  nome?: InputMaybe<StringFilter>;
  categoria?: InputMaybe<StringFilter>;
  area?: InputMaybe<StringFilter>;
  nivel?: InputMaybe<StringFilter>;
  instituicao?: InputMaybe<StringFilter>;
  instituicao_url?: InputMaybe<StringFilter>;
  ano?: InputMaybe<NumberFilter>;
  credencial_url?: InputMaybe<StringFilter>;
  descricao?: InputMaybe<StringFilter>;
  destaque?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SkillsConnectionEdges = {
  __typename?: 'SkillsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Skills>;
};

export type SkillsConnection = Connection & {
  __typename?: 'SkillsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SkillsConnectionEdges>>>;
};

export type Posts = Node & Document & {
  __typename?: 'Posts';
  titulo: Scalars['String']['output'];
  resumo: Scalars['String']['output'];
  data: Scalars['String']['output'];
  publicar_em?: Maybe<Scalars['String']['output']>;
  capa_url?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  fonte_externa_url?: Maybe<Scalars['String']['output']>;
  fonte_externa_nome?: Maybe<Scalars['String']['output']>;
  idioma?: Maybe<Scalars['String']['output']>;
  rascunho?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PostsBodyVideoEmbedFilter = {
  src?: InputMaybe<StringFilter>;
  legenda?: InputMaybe<StringFilter>;
};

export type PostsBodyFilter = {
  VideoEmbed?: InputMaybe<PostsBodyVideoEmbedFilter>;
};

export type PostsFilter = {
  titulo?: InputMaybe<StringFilter>;
  resumo?: InputMaybe<StringFilter>;
  data?: InputMaybe<DatetimeFilter>;
  publicar_em?: InputMaybe<DatetimeFilter>;
  capa_url?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  fonte_externa_url?: InputMaybe<StringFilter>;
  fonte_externa_nome?: InputMaybe<StringFilter>;
  idioma?: InputMaybe<StringFilter>;
  rascunho?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<PostsBodyFilter>;
};

export type PostsConnectionEdges = {
  __typename?: 'PostsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Posts>;
};

export type PostsConnection = Connection & {
  __typename?: 'PostsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostsConnectionEdges>>>;
};

export type Atualizacoes = Node & Document & {
  __typename?: 'Atualizacoes';
  data: Scalars['String']['output'];
  tipo: Scalars['String']['output'];
  titulo: Scalars['String']['output'];
  referencia_slug?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AtualizacoesFilter = {
  data?: InputMaybe<DatetimeFilter>;
  tipo?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  referencia_slug?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AtualizacoesConnectionEdges = {
  __typename?: 'AtualizacoesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Atualizacoes>;
};

export type AtualizacoesConnection = Connection & {
  __typename?: 'AtualizacoesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AtualizacoesConnectionEdges>>>;
};

export type Agora = Node & Document & {
  __typename?: 'Agora';
  atualizado_em: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AgoraFilter = {
  atualizado_em?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AgoraConnectionEdges = {
  __typename?: 'AgoraConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Agora>;
};

export type AgoraConnection = Connection & {
  __typename?: 'AgoraConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AgoraConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTimeline: Timeline;
  createTimeline: Timeline;
  updateProjetos: Projetos;
  createProjetos: Projetos;
  updateSkills: Skills;
  createSkills: Skills;
  updatePosts: Posts;
  createPosts: Posts;
  updateAtualizacoes: Atualizacoes;
  createAtualizacoes: Atualizacoes;
  updateAgora: Agora;
  createAgora: Agora;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTimelineArgs = {
  relativePath: Scalars['String']['input'];
  params: TimelineMutation;
};


export type MutationCreateTimelineArgs = {
  relativePath: Scalars['String']['input'];
  params: TimelineMutation;
};


export type MutationUpdateProjetosArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjetosMutation;
};


export type MutationCreateProjetosArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjetosMutation;
};


export type MutationUpdateSkillsArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillsMutation;
};


export type MutationCreateSkillsArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillsMutation;
};


export type MutationUpdatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationCreatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationUpdateAtualizacoesArgs = {
  relativePath: Scalars['String']['input'];
  params: AtualizacoesMutation;
};


export type MutationCreateAtualizacoesArgs = {
  relativePath: Scalars['String']['input'];
  params: AtualizacoesMutation;
};


export type MutationUpdateAgoraArgs = {
  relativePath: Scalars['String']['input'];
  params: AgoraMutation;
};


export type MutationCreateAgoraArgs = {
  relativePath: Scalars['String']['input'];
  params: AgoraMutation;
};

export type DocumentUpdateMutation = {
  timeline?: InputMaybe<TimelineMutation>;
  projetos?: InputMaybe<ProjetosMutation>;
  skills?: InputMaybe<SkillsMutation>;
  posts?: InputMaybe<PostsMutation>;
  atualizacoes?: InputMaybe<AtualizacoesMutation>;
  agora?: InputMaybe<AgoraMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  timeline?: InputMaybe<TimelineMutation>;
  projetos?: InputMaybe<ProjetosMutation>;
  skills?: InputMaybe<SkillsMutation>;
  posts?: InputMaybe<PostsMutation>;
  atualizacoes?: InputMaybe<AtualizacoesMutation>;
  agora?: InputMaybe<AgoraMutation>;
};

export type TimelineMutation = {
  cargo?: InputMaybe<Scalars['String']['input']>;
  empresa?: InputMaybe<Scalars['String']['input']>;
  empresa_url?: InputMaybe<Scalars['String']['input']>;
  inicio?: InputMaybe<Scalars['String']['input']>;
  fim?: InputMaybe<Scalars['String']['input']>;
  local?: InputMaybe<Scalars['String']['input']>;
  tipo?: InputMaybe<Scalars['String']['input']>;
  resumo?: InputMaybe<Scalars['String']['input']>;
  destaques?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  destaque?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProjetosMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  inicio?: InputMaybe<Scalars['String']['input']>;
  fim?: InputMaybe<Scalars['String']['input']>;
  cliente?: InputMaybe<Scalars['String']['input']>;
  papel?: InputMaybe<Scalars['String']['input']>;
  resumo?: InputMaybe<Scalars['String']['input']>;
  problema?: InputMaybe<Scalars['String']['input']>;
  abordagem?: InputMaybe<Scalars['String']['input']>;
  resultado?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  destaque?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SkillsMutation = {
  nome?: InputMaybe<Scalars['String']['input']>;
  categoria?: InputMaybe<Scalars['String']['input']>;
  area?: InputMaybe<Scalars['String']['input']>;
  nivel?: InputMaybe<Scalars['String']['input']>;
  instituicao?: InputMaybe<Scalars['String']['input']>;
  instituicao_url?: InputMaybe<Scalars['String']['input']>;
  ano?: InputMaybe<Scalars['Float']['input']>;
  credencial_url?: InputMaybe<Scalars['String']['input']>;
  descricao?: InputMaybe<Scalars['String']['input']>;
  destaque?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PostsMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  resumo?: InputMaybe<Scalars['String']['input']>;
  data?: InputMaybe<Scalars['String']['input']>;
  publicar_em?: InputMaybe<Scalars['String']['input']>;
  capa_url?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  fonte_externa_url?: InputMaybe<Scalars['String']['input']>;
  fonte_externa_nome?: InputMaybe<Scalars['String']['input']>;
  idioma?: InputMaybe<Scalars['String']['input']>;
  rascunho?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AtualizacoesMutation = {
  data?: InputMaybe<Scalars['String']['input']>;
  tipo?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  referencia_slug?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AgoraMutation = {
  atualizado_em?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TimelinePartsFragment = { __typename: 'Timeline', cargo: string, empresa: string, empresa_url?: string | null, inicio: string, fim?: string | null, local?: string | null, tipo?: string | null, resumo?: string | null, destaques?: Array<string | null> | null, tags?: Array<string | null> | null, destaque?: boolean | null, body?: any | null };

export type ProjetosPartsFragment = { __typename: 'Projetos', titulo: string, subtitulo?: string | null, status: string, inicio: string, fim?: string | null, cliente?: string | null, papel: string, resumo: string, problema?: string | null, abordagem?: string | null, resultado?: string | null, link?: string | null, tags?: Array<string | null> | null, destaque?: boolean | null, body?: any | null };

export type SkillsPartsFragment = { __typename: 'Skills', nome: string, categoria: string, area: string, nivel?: string | null, instituicao?: string | null, instituicao_url?: string | null, ano?: number | null, credencial_url?: string | null, descricao?: string | null, destaque?: boolean | null, body?: any | null };

export type PostsPartsFragment = { __typename: 'Posts', titulo: string, resumo: string, data: string, publicar_em?: string | null, capa_url?: string | null, tags?: Array<string | null> | null, fonte_externa_url?: string | null, fonte_externa_nome?: string | null, idioma?: string | null, rascunho?: boolean | null, body?: any | null };

export type AtualizacoesPartsFragment = { __typename: 'Atualizacoes', data: string, tipo: string, titulo: string, referencia_slug?: string | null, body?: any | null };

export type AgoraPartsFragment = { __typename: 'Agora', atualizado_em: string, body?: any | null };

export type TimelineQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TimelineQuery = { __typename?: 'Query', timeline: { __typename: 'Timeline', id: string, cargo: string, empresa: string, empresa_url?: string | null, inicio: string, fim?: string | null, local?: string | null, tipo?: string | null, resumo?: string | null, destaques?: Array<string | null> | null, tags?: Array<string | null> | null, destaque?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TimelineConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TimelineFilter>;
}>;


export type TimelineConnectionQuery = { __typename?: 'Query', timelineConnection: { __typename?: 'TimelineConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TimelineConnectionEdges', cursor: string, node?: { __typename: 'Timeline', id: string, cargo: string, empresa: string, empresa_url?: string | null, inicio: string, fim?: string | null, local?: string | null, tipo?: string | null, resumo?: string | null, destaques?: Array<string | null> | null, tags?: Array<string | null> | null, destaque?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProjetosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjetosQuery = { __typename?: 'Query', projetos: { __typename: 'Projetos', id: string, titulo: string, subtitulo?: string | null, status: string, inicio: string, fim?: string | null, cliente?: string | null, papel: string, resumo: string, problema?: string | null, abordagem?: string | null, resultado?: string | null, link?: string | null, tags?: Array<string | null> | null, destaque?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjetosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjetosFilter>;
}>;


export type ProjetosConnectionQuery = { __typename?: 'Query', projetosConnection: { __typename?: 'ProjetosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjetosConnectionEdges', cursor: string, node?: { __typename: 'Projetos', id: string, titulo: string, subtitulo?: string | null, status: string, inicio: string, fim?: string | null, cliente?: string | null, papel: string, resumo: string, problema?: string | null, abordagem?: string | null, resultado?: string | null, link?: string | null, tags?: Array<string | null> | null, destaque?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SkillsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SkillsQuery = { __typename?: 'Query', skills: { __typename: 'Skills', id: string, nome: string, categoria: string, area: string, nivel?: string | null, instituicao?: string | null, instituicao_url?: string | null, ano?: number | null, credencial_url?: string | null, descricao?: string | null, destaque?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SkillsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillsFilter>;
}>;


export type SkillsConnectionQuery = { __typename?: 'Query', skillsConnection: { __typename?: 'SkillsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SkillsConnectionEdges', cursor: string, node?: { __typename: 'Skills', id: string, nome: string, categoria: string, area: string, nivel?: string | null, instituicao?: string | null, instituicao_url?: string | null, ano?: number | null, credencial_url?: string | null, descricao?: string | null, destaque?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PostsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostsQuery = { __typename?: 'Query', posts: { __typename: 'Posts', id: string, titulo: string, resumo: string, data: string, publicar_em?: string | null, capa_url?: string | null, tags?: Array<string | null> | null, fonte_externa_url?: string | null, fonte_externa_nome?: string | null, idioma?: string | null, rascunho?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
}>;


export type PostsConnectionQuery = { __typename?: 'Query', postsConnection: { __typename?: 'PostsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostsConnectionEdges', cursor: string, node?: { __typename: 'Posts', id: string, titulo: string, resumo: string, data: string, publicar_em?: string | null, capa_url?: string | null, tags?: Array<string | null> | null, fonte_externa_url?: string | null, fonte_externa_nome?: string | null, idioma?: string | null, rascunho?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AtualizacoesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AtualizacoesQuery = { __typename?: 'Query', atualizacoes: { __typename: 'Atualizacoes', id: string, data: string, tipo: string, titulo: string, referencia_slug?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AtualizacoesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AtualizacoesFilter>;
}>;


export type AtualizacoesConnectionQuery = { __typename?: 'Query', atualizacoesConnection: { __typename?: 'AtualizacoesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AtualizacoesConnectionEdges', cursor: string, node?: { __typename: 'Atualizacoes', id: string, data: string, tipo: string, titulo: string, referencia_slug?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AgoraQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AgoraQuery = { __typename?: 'Query', agora: { __typename: 'Agora', id: string, atualizado_em: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AgoraConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AgoraFilter>;
}>;


export type AgoraConnectionQuery = { __typename?: 'Query', agoraConnection: { __typename?: 'AgoraConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AgoraConnectionEdges', cursor: string, node?: { __typename: 'Agora', id: string, atualizado_em: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const TimelinePartsFragmentDoc = gql`
    fragment TimelineParts on Timeline {
  __typename
  cargo
  empresa
  empresa_url
  inicio
  fim
  local
  tipo
  resumo
  destaques
  tags
  destaque
  body
}
    `;
export const ProjetosPartsFragmentDoc = gql`
    fragment ProjetosParts on Projetos {
  __typename
  titulo
  subtitulo
  status
  inicio
  fim
  cliente
  papel
  resumo
  problema
  abordagem
  resultado
  link
  tags
  destaque
  body
}
    `;
export const SkillsPartsFragmentDoc = gql`
    fragment SkillsParts on Skills {
  __typename
  nome
  categoria
  area
  nivel
  instituicao
  instituicao_url
  ano
  credencial_url
  descricao
  destaque
  body
}
    `;
export const PostsPartsFragmentDoc = gql`
    fragment PostsParts on Posts {
  __typename
  titulo
  resumo
  data
  publicar_em
  capa_url
  tags
  fonte_externa_url
  fonte_externa_nome
  idioma
  rascunho
  body
}
    `;
export const AtualizacoesPartsFragmentDoc = gql`
    fragment AtualizacoesParts on Atualizacoes {
  __typename
  data
  tipo
  titulo
  referencia_slug
  body
}
    `;
export const AgoraPartsFragmentDoc = gql`
    fragment AgoraParts on Agora {
  __typename
  atualizado_em
  body
}
    `;
export const TimelineDocument = gql`
    query timeline($relativePath: String!) {
  timeline(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TimelineParts
  }
}
    ${TimelinePartsFragmentDoc}`;
export const TimelineConnectionDocument = gql`
    query timelineConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TimelineFilter) {
  timelineConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TimelineParts
      }
    }
  }
}
    ${TimelinePartsFragmentDoc}`;
export const ProjetosDocument = gql`
    query projetos($relativePath: String!) {
  projetos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjetosParts
  }
}
    ${ProjetosPartsFragmentDoc}`;
export const ProjetosConnectionDocument = gql`
    query projetosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjetosFilter) {
  projetosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjetosParts
      }
    }
  }
}
    ${ProjetosPartsFragmentDoc}`;
export const SkillsDocument = gql`
    query skills($relativePath: String!) {
  skills(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SkillsParts
  }
}
    ${SkillsPartsFragmentDoc}`;
export const SkillsConnectionDocument = gql`
    query skillsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SkillsFilter) {
  skillsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SkillsParts
      }
    }
  }
}
    ${SkillsPartsFragmentDoc}`;
export const PostsDocument = gql`
    query posts($relativePath: String!) {
  posts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostsParts
  }
}
    ${PostsPartsFragmentDoc}`;
export const PostsConnectionDocument = gql`
    query postsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostsFilter) {
  postsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostsParts
      }
    }
  }
}
    ${PostsPartsFragmentDoc}`;
export const AtualizacoesDocument = gql`
    query atualizacoes($relativePath: String!) {
  atualizacoes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AtualizacoesParts
  }
}
    ${AtualizacoesPartsFragmentDoc}`;
export const AtualizacoesConnectionDocument = gql`
    query atualizacoesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AtualizacoesFilter) {
  atualizacoesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AtualizacoesParts
      }
    }
  }
}
    ${AtualizacoesPartsFragmentDoc}`;
export const AgoraDocument = gql`
    query agora($relativePath: String!) {
  agora(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AgoraParts
  }
}
    ${AgoraPartsFragmentDoc}`;
export const AgoraConnectionDocument = gql`
    query agoraConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AgoraFilter) {
  agoraConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AgoraParts
      }
    }
  }
}
    ${AgoraPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      timeline(variables: TimelineQueryVariables, options?: C): Promise<{data: TimelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineQueryVariables, query: string}> {
        return requester<{data: TimelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineQueryVariables, query: string}, TimelineQueryVariables>(TimelineDocument, variables, options);
      },
    timelineConnection(variables?: TimelineConnectionQueryVariables, options?: C): Promise<{data: TimelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineConnectionQueryVariables, query: string}> {
        return requester<{data: TimelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineConnectionQueryVariables, query: string}, TimelineConnectionQueryVariables>(TimelineConnectionDocument, variables, options);
      },
    projetos(variables: ProjetosQueryVariables, options?: C): Promise<{data: ProjetosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosQueryVariables, query: string}> {
        return requester<{data: ProjetosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosQueryVariables, query: string}, ProjetosQueryVariables>(ProjetosDocument, variables, options);
      },
    projetosConnection(variables?: ProjetosConnectionQueryVariables, options?: C): Promise<{data: ProjetosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosConnectionQueryVariables, query: string}> {
        return requester<{data: ProjetosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosConnectionQueryVariables, query: string}, ProjetosConnectionQueryVariables>(ProjetosConnectionDocument, variables, options);
      },
    skills(variables: SkillsQueryVariables, options?: C): Promise<{data: SkillsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsQueryVariables, query: string}> {
        return requester<{data: SkillsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsQueryVariables, query: string}, SkillsQueryVariables>(SkillsDocument, variables, options);
      },
    skillsConnection(variables?: SkillsConnectionQueryVariables, options?: C): Promise<{data: SkillsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsConnectionQueryVariables, query: string}> {
        return requester<{data: SkillsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsConnectionQueryVariables, query: string}, SkillsConnectionQueryVariables>(SkillsConnectionDocument, variables, options);
      },
    posts(variables: PostsQueryVariables, options?: C): Promise<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}> {
        return requester<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}, PostsQueryVariables>(PostsDocument, variables, options);
      },
    postsConnection(variables?: PostsConnectionQueryVariables, options?: C): Promise<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}> {
        return requester<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}, PostsConnectionQueryVariables>(PostsConnectionDocument, variables, options);
      },
    atualizacoes(variables: AtualizacoesQueryVariables, options?: C): Promise<{data: AtualizacoesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AtualizacoesQueryVariables, query: string}> {
        return requester<{data: AtualizacoesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AtualizacoesQueryVariables, query: string}, AtualizacoesQueryVariables>(AtualizacoesDocument, variables, options);
      },
    atualizacoesConnection(variables?: AtualizacoesConnectionQueryVariables, options?: C): Promise<{data: AtualizacoesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AtualizacoesConnectionQueryVariables, query: string}> {
        return requester<{data: AtualizacoesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AtualizacoesConnectionQueryVariables, query: string}, AtualizacoesConnectionQueryVariables>(AtualizacoesConnectionDocument, variables, options);
      },
    agora(variables: AgoraQueryVariables, options?: C): Promise<{data: AgoraQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgoraQueryVariables, query: string}> {
        return requester<{data: AgoraQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgoraQueryVariables, query: string}, AgoraQueryVariables>(AgoraDocument, variables, options);
      },
    agoraConnection(variables?: AgoraConnectionQueryVariables, options?: C): Promise<{data: AgoraConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgoraConnectionQueryVariables, query: string}> {
        return requester<{data: AgoraConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgoraConnectionQueryVariables, query: string}, AgoraConnectionQueryVariables>(AgoraConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/d2190664-7e6a-4cbe-b628-14fb41d87433/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  